---
- name: Search restic and profiles.yaml
  hosts: all
  gather_facts: false

  tasks:
    - name: Search restic in /usr/bin
      find:
        paths: /usr/bin
        patterns: restic
      register: found_restic

    - name: restic files
      debug:
        msg: "restic {{ 'find' if found_restic.files else 'not find' }} in /usr/bin"

    - name: cmd restic
      ansible.builtin.command:
        cmd: resticprofile status
      register: restic_command_output
      when: found_restic.files

    - name: output restic
      ansible.builtin.debug:
        var: restic_command_output.stdout_lines
      when: found_restic.files