
---
- name: Search restic, resticprofile
  hosts: all
  gather_facts: true  #Включаем сбор фактов, чтобы получить IP-адреса

  tasks:
    - name: Search restic in /usr/bin
      find:
        paths: /usr/bin
        patterns: restic
      register: found_restic

    - name: Command restic
      ansible.builtin.command:
        cmd: restic
      register: restic_command_output
      when: found_restic.files

    - name: Save report to file
      ansible.builtin.lineinfile:
        path: /tmp/file01.txt
        line: |
          [{{ inventory_hostname }} ({{ ansible_host }})]
          {{ restic_command_output.stdout | default("Нет вывода") }} #Если закоментить данную строку то получим только IP-адреса машин, где присутвует resticprofile
      delegate_to: localhost
      when: found_restic.files
